events {}
http {
    upstream backend_nodes {
        server backend:3000;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_nodes;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            return 200 '{"message": "Gateway ready. Query /api/hits or /api/health"}';
            add_header Content-Type application/json;
        }
    }
}